create table konto (id bigint generated by default as identity, email varchar(255) unique, nachname varchar(255), passwort varchar(255), vorname varchar(255), primary key (id));


insert into konto (vorname, nachname, email, passwort) values ('Testa', 'Rossa', 'test2@testa.de', 'keins');